# Generated by Django 3.1.1 on 2020-11-09 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kicks',
            new_name='Kick',
        ),
    ]
