# Generated by Django 3.1.1 on 2020-11-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201109_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kick',
            name='releasedate',
            field=models.CharField(max_length=100),
        ),
    ]
