# Generated by Django 3.1.1 on 2020-11-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201111_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='kick',
            name='laces',
            field=models.ManyToManyField(to='main_app.Lace'),
        ),
    ]
